#!/usr/bin/env php
<?php

use Azulphp\Commands\CommandManager;
use Azulphp\Core\App;

const BASE_PATH = __DIR__ . '/';

require_once BASE_PATH . '/vendor/autoload.php';
require_once BASE_PATH . '/vendor/azulphp/framework/src/Helpers/functions.php';
require_once BASE_PATH.'/bootstrap/app.php';

App::resolve(CommandManager::class)->handle();