#!/usr/bin/env php
<?php

use Azulphp\App;
use Azulphp\Commands\CommandManager;

const BASE_PATH = __DIR__ . '/';

require_once BASE_PATH . '/vendor/autoload.php';
require_once BASE_PATH . '/vendor/azulphp/framework/src/Helpers/functions.php';
require_once BASE_PATH . '/bootstrap.php';

App::resolve(CommandManager::class)->handle();